ccflags-y += -Idrivers/media/platform/msm/camera_v2-whyred
ccflags-y += -Idrivers/media/platform/msm/camera_v2-whyred/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2-whyred/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-whyred/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-whyred/msm_buf_mgr/
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
