ccflags-y += -Idrivers/media/platform/msm/camera_v2-whyred/
ccflags-y += -Idrivers/media/platform/msm/camera_v2-whyred/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-whyred/sensor
ccflags-y += -Idrivers/media/platform/msm/camera_v2-whyred/sensor/cci
ccflags-y += -Idrivers/misc/
obj-$(CONFIG_MSMB_CAMERA)   += msm_camera_cci_i2c.o msm_camera_qup_i2c.o msm_camera_spi.o msm_camera_dt_util.o msm_camera_tz_i2c.o
