ccflags-y += -Idrivers/media/platform/msm/camera_v2-whyred/jpeg_10
ccflags-y += -Idrivers/media/platform/msm/camera_v2-whyred/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-whyred/common

obj-$(CONFIG_MSMB_JPEG) += msm_jpeg_dev.o msm_jpeg_sync.o msm_jpeg_core.o msm_jpeg_hw.o msm_jpeg_platform.o
