ccflags-y += -Idrivers/media/platform/msm/camera_v2-whyred
ccflags-y += -Idrivers/media/platform/msm/camera_v2-whyred/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-whyred/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-whyred/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_ois.o
